{{- if .Values.cm.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-vip-cloud-provider.name" . }}-cm
  namespace: {{ .Release.Namespace | default "kube-system" }}
data:
{{- range $key, $value := .Values.cm.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
