apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-vip-cloud-provider.name" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      {{- include "kube-vip-cloud-provider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-vip-cloud-provider.selectorLabels" . | nindent 8 }}
      annotations:
        configmap-checksum: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - command:
            - /kube-vip-cloud-provider
            - --leader-elect-resource-name=kube-vip-cloud-controller
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          name: {{ include "kube-vip-cloud-provider.name" . }}
          env:
          - name: KUBEVIP_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: KUBEVIP_CONFIG_MAP
            value: {{ include "kube-vip-cloud-provider.name" . }}-cm
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ include "kube-vip-cloud-provider.name" . }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
