# Default values for kube-vip-cloud-provider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicasCount: 1

image:
  repository: kubevip/kube-vip-cloud-provider
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "v0.0.4"

## Cloud Provider ConfigMap
## CIDR blocks , IP ranges [start address - end address]
## Multiple pools by CIDR per Namespace, Multiple IP ranges per Namespace (handles overlapping ranges)

# cm:
#   data:
#     cidr-default: 192.168.0.200/29                      # CIDR-based IP range for use in the default Namespace
#     range-development: 192.168.0.210-192.168.0.219      # Range-based IP range for use in the development Namespace
#     cidr-finance: 192.168.0.220/29,192.168.0.230/29     # Multiple CIDR-based ranges for use in the finance Namespace
#     cidr-global: 192.168.0.240/29

cm:
  data: {}

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
      - weight: 10
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists
